<div class="container">

    <div class="row justify-content-center">
        <div class="col-md-8">
            <h1 class="my-5">Materi Pembelajaran</h1>
            <iframe width="755" height="427" src=" https://www.youtube.com/embed/SuVMobAoToc?modestbranding=1&amp;rel=0&amp;iv_load_policy=3&amp;enablejsapi=1" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen=""></iframe>

            <p class="my-5">Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui in voluptas aut? Impedit, ducimus non harum iure quasi quisquam rerum excepturi? Praesentium quae repudiandae voluptatibus nobis necessitatibus inventore deleniti nulla?. Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero ipsam magni minima ex aliquam iste perferendis consectetur temporibus, sit nostrum unde dicta, quia molestiae atque molestias beatae minus voluptate dolorum? Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consequuntur, atque necessitatibus! Laudantium mollitia ratione nesciunt quas, dolorum placeat perspiciatis nemo, minima odio ducimus incidunt modi fugit iure sequi, labore provident. Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi quia nam error perspiciatis, neque laudantium expedita eligendi totam dolorum. Quidem iure quos pariatur asperiores in ea nisi facere at. Commodi! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Laudantium doloribus aliquid illum distinctio doloremque voluptate est autem veritatis aut. Optio explicabo, eum eaque ducimus aut facere accusamus reprehenderit id deleniti?</p>

            <p class="my-5">Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui in voluptas aut? Impedit, ducimus non harum iure quasi quisquam rerum excepturi? Praesentium quae repudiandae voluptatibus nobis necessitatibus inventore deleniti nulla?. Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero ipsam magni minima ex aliquam iste perferendis consectetur temporibus, sit nostrum unde dicta, quia molestiae atque molestias beatae minus voluptate dolorum? Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consequuntur, atque necessitatibus! Laudantium mollitia ratione nesciunt quas, dolorum placeat perspiciatis nemo, minima odio ducimus incidunt modi fugit iure sequi, labore provident. Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi quia nam error perspiciatis, neque laudantium expedita eligendi totam dolorum. Quidem iure quos pariatur asperiores in ea nisi facere at. Commodi! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Laudantium doloribus aliquid illum distinctio doloremque voluptate est autem veritatis aut. Optio explicabo, eum eaque ducimus aut facere accusamus reprehenderit id deleniti?</p>

            <p class="my-5">Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui in voluptas aut? Impedit, ducimus non harum iure quasi quisquam rerum excepturi? Praesentium quae repudiandae voluptatibus nobis necessitatibus inventore deleniti nulla?. Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero ipsam magni minima ex aliquam iste perferendis consectetur temporibus, sit nostrum unde dicta, quia molestiae atque molestias beatae minus voluptate dolorum? Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consequuntur, atque necessitatibus! Laudantium mollitia ratione nesciunt quas, dolorum placeat perspiciatis nemo, minima odio ducimus incidunt modi fugit iure sequi, labore provident. Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi quia nam error perspiciatis, neque laudantium expedita eligendi totam dolorum. Quidem iure quos pariatur asperiores in ea nisi facere at. Commodi! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Laudantium doloribus aliquid illum distinctio doloremque voluptate est autem veritatis aut. Optio explicabo, eum eaque ducimus aut facere accusamus reprehenderit id deleniti?</p>

            <p class="my-5">Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui in voluptas aut? Impedit, ducimus non harum iure quasi quisquam rerum excepturi? Praesentium quae repudiandae voluptatibus nobis necessitatibus inventore deleniti nulla?. Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero ipsam magni minima ex aliquam iste perferendis consectetur temporibus, sit nostrum unde dicta, quia molestiae atque molestias beatae minus voluptate dolorum? Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consequuntur, atque necessitatibus! Laudantium mollitia ratione nesciunt quas, dolorum placeat perspiciatis nemo, minima odio ducimus incidunt modi fugit iure sequi, labore provident. Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi quia nam error perspiciatis, neque laudantium expedita eligendi totam dolorum. Quidem iure quos pariatur asperiores in ea nisi facere at. Commodi! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Laudantium doloribus aliquid illum distinctio doloremque voluptate est autem veritatis aut. Optio explicabo, eum eaque ducimus aut facere accusamus reprehenderit id deleniti?</p>
        </div>
    </div>
</div>